  # Workflow'a bir isim verelim
  name: Deploy Frontend to Server

  # Bu workflow'un ne zaman çalışacağını belirliyoruz:
  # "main" branch'ine her kod gönderildiğinde (push) tetiklenecek.
  # Eğer branch'inizin adı "master" ise, "main"i "master" olarak değiştirin.
  on:
    push:
      branches:
        - main

  jobs:
    deploy:
      # Bu job'un çalışacağı sanal makine tipi
      runs-on: ubuntu-latest

      steps:
        # 1. Adım: Repodaki kodları sanal makineye indirir.
        - name: Checkout code
          uses: actions/checkout@v3

        # 2. Adım: Sunucuya SSH ile bağlanır ve script'i çalıştırır.
        # Daha önce eklediğimiz sırları (secrets) burada kullanır.
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd ${{ secrets.PROJECT_PATH }}
              echo ">>> Pulling frontend code..."
              cd ./Tournavel-Admin && git pull && cd ..
              echo ">>> Building Docker images..."
              docker-compose build --no-cache frontend 
              echo ">>> Restarting services..."
              docker-compose up -d --force-recreate frontend
